//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WriteCard.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WRITECARD_DIALOG            102
#define IDD_PROPPAGE_WRITEISO6C         106
#define IDD_DIALOG_READISO6C            107
#define IDD_PROPPAGE_PARAM              108
#define IDD_DIALOG_READISO6B            109
#define IDD_PROPPAGE_WRITEISO6B         110
#define IDD_PROPPAGE_CONNECT            111
#define IDR_MAINFRAME                   128
#define IDR_ENGLISH                     129
#define IDR_CHINESE                     130
#define IDI_ICON_OK                     133
#define IDI_ICON_ERR                    134
#define IDI_ICON_WAIT                   135
#define IDI_ICONNone                    136
#define IDI_ICONRED                     137
#define IDC_STATIC_ConnectMode          1000
#define IDC_RADIO_ConnectRS232          1001
#define IDC_RADIO_ConnectUSB            1002
#define IDC_BUTTON1                     1003
#define IDC_STATIC_CONLanguage          1003
#define IDC_BUTTON_CONNECTDIS           1004
#define IDC_RADIO_CONEnglish            1005
#define IDC_RADIO_CONChinese            1006
#define IDC_STATIC_HANDVER              1007
#define IDC_STATIC_CONRS232             1007
#define IDC_EDIT_HANDVER                1008
#define IDC_COMBO1                      1008
#define IDC_STATIC_SOFTVER              1009
#define IDC_STATIC_SerialPort           1009
#define IDC_BUTTON2                     1010
#define IDC_BUTTON_ERROR                1010
#define IDC_BUTTON_DELONE               1010
#define IDC_EDIT_HANDVER2               1010
#define IDC_STATIC_BASICPARAM           1011
#define IDC_STATIC_MINFREQ              1012
#define IDC_COMBO_MINFREQ               1013
#define IDC_STATIC_MAXFREQ              1014
#define IDC_COMBO_MAXFREQ               1015
#define IDC_STATIC_OUTPOWER             1016
#define IDC_EDIT_OUTPOWER               1017
#define IDC_STATIC_TAGOPT               1018
#define IDC_RADIO_ISO180006B            1019
#define IDC_RADIO_ISO180006C            1020
#define IDC_STATIC_MSDATAF              1021
#define IDC_STATIC_MSDATABANK           1022
#define IDC_RADIO1_Hex16                1023
#define IDC_RADIO1_Hex10                1024
#define IDC_RADIO_DATAID                1025
#define IDC_RADIO_DATAUSER              1026
#define IDC_RADIO_DATATID               1027
#define IDC_STATIC_HARDID               1028
#define IDC_EDIT_HARDID                 1029
#define IDC_STATIC_READBET              1030
#define IDC_COMBO_READBET               1031
#define IDC_STATIC_OUTPUTBET            1032
#define IDC_EDIT_OUTPUTBET              1033
#define IDC_STATIC_CODESET              1034
#define IDC_STATIC_DATABIT              1035
#define IDC_STATIC_W6CEXAMPLE           1036
#define IDC_STATIC_BE                   1037
#define IDC_STATIC_XU                   1038
#define IDC_STATIC_AF                   1039
#define IDC_STATIC_XUHAO                1040
#define IDC_STATIC_BUCHANG              1041
#define IDC_LIST_INDATA                 1042
#define IDC_STATIC_MAKENUM              1043
#define IDC_STATIC_LISTD                1044
#define IDC_STATIC_SAVEOPT              1045
#define IDC_STATIC_NUMT                 1046
#define IDC_STATIC_FINISHNUM            1047
#define IDC_BUTTON_DATA                 1048
#define IDC_BUTTON_FILE                 1049
#define IDC_EDIT_BEGIN                  1050
#define IDC_EDIT_COUNT                  1051
#define IDC_EDIT_SUM                    1052
#define IDC_EDIT_XXXX                   1053
#define IDC_COMBO_WORD                  1054
#define IDC_STATIC_SHENGNUM             1055
#define IDC_STATIC_SUCCESSNUM           1056
#define IDC_BUTTON_WRITE                1057
#define IDC_BUTTON_STOP                 1058
#define IDC_COMBO_COM                   1059
#define IDC_STATIC_FAILNUM              1059
#define IDC_BUTTON_CONNECT              1060
#define IDC_STATIC_WRITEOP              1060
#define IDC_BUTTON_DISCONNECT           1061
#define IDC_STATIC_BETT                 1061
#define IDC_CHECK_EPC                   1062
#define IDC_CHECK_USE                   1063
#define IDC_CHECK_PASS                  1064
#define IDC_LIST_OUTDATA                1065
#define IDC_COMBO6                      1065
#define IDC_EDIT_TIME                   1066
#define IDC_BUTTON_DELOUT               1067
#define IDC_RADIO23_NoAlarm_6C          1067
#define IDC_CHECK_LOCKEPC_PASS          1068
#define IDC_RADIO24_Alarm_6C            1068
#define IDC_STATIC_PIC                  1069
#define IDC_EDIT12                      1069
#define IDC_STATIC_DIS                  1070
#define IDC_STATIC_OUT                  1071
#define IDC_CHECK_LOCKEPC_Neverwriteable 1072
#define IDC_BUTTON_MOVE                 1073
#define IDC_EDIT_BEFOR                  1074
#define IDC_EASALARM_STATIC             1074
#define IDC_CHECK_BEFOR                 1075
#define IDC_EDIT_END                    1076
#define IDC_CHECK_END                   1077
#define IDC_EDIT_TOTAL                  1078
#define IDC_EDIT_FALSH                  1079
#define IDC_EDIT_MOD                    1080
#define IDC_EDIT_TRUE                   1081
#define IDC_EDIT_FALSE                  1082
#define IDC_BUTTON_DELALL               1083
#define IDC_LIST_SHOW                   1084
#define IDC_STATIC_FINLIST              1084
#define IDC_CHECK_TID                   1085
#define IDC_STATIC_WWriteDATA           1085
#define IDC_STATIC_STATTIP              1086
#define IDC_CHECK_USER                  1087
#define IDC_STATIC_WWriteSTAT           1087
#define IDC_EDIT_TIDB                   1088
#define IDC_STATIC_FWriteData           1088
#define IDC_EDIT_PASSB                  1089
#define IDC_CHECK_LOCKEPC_EAS_ALARM     1089
#define IDC_EDIT_USERB                  1090
#define IDC_EDIT_TIDL                   1091
#define IDC_EDIT_PASSL                  1092
#define IDC_EDIT_USERL                  1093
#define IDC_STATIC_R6ReadList           1094
#define IDC_STATIC_IN                   1095
#define IDC_STATIC_R6DATAPART           1095
#define IDC_RADIO_EPC                   1096
#define IDC_STATIC_TIDSTARTPOS          1096
#define IDC_RADIO_USER                  1097
#define IDC_STATIC_PASSSTARTPOS         1097
#define IDC_RADIO_PASS                  1098
#define IDC_STATIC_USERSTARTPOS         1098
#define IDC_BUTTON_INDATA               1099
#define IDC_STATIC_TIDLEN               1099
#define IDC_BUTTON_SUCCESS              1100
#define IDC_STATIC_PASSLEN              1100
#define IDC_BUTTON_SAVE                 1101
#define IDC_BUTTON4                     1102
#define IDC_BUTTON_SAVE2                1102
#define IDC_STATIC_ProtectEPCA          1103
#define IDC_STATIC_USERLEN              1103
#define IDC_EDIT_USERPASS               1104
#define IDC_STATIC_R6BETTIME            1104
#define IDC_STATIC_USERPASS             1105
#define IDC_STATIC_R6ReadStat           1105
#define IDC_STATIC_PASSFR               1106
#define IDC_STATIC_R6ReadData           1106
#define IDC_STATIC_GroupREAD            1107
#define IDC_STATIC_SelectaTagAE_6C      1218
#define IDC_BUTTON5_SetAlarm_6C         1225
#define IDC_CHECK7_EasAlarm_6C          1226
#define IDC_STATIC_AlarmCC_6C           1232
#define IDC_STATIC_AccessPSDDA_6C       1233
#define IDC_CHECK1_PERFIX               1340
#define IDC_STATIC_PERFIXT              1341
#define IDC_CHECK1_LF                   1342
#define IDC_STATIC_MSDATAB              1343
#define IDC_EDIT2_PERFIXVALUE           1344
#define IDC_STATIC_MSDATAStart          1345
#define IDC_EDIT2_MSDATAStart           1346
#define IDC_STATIC_MSDATALEN            1347
#define IDC_EDIT2_MSDATALEN             1348
#define IDC_BUTTON1_MSUPDATE            1349
#define IDC_BUTTON1_MSGET               1350

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1108
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
